/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'live.drome.sketch'

export { $nsid }

/** A live-coded music sketch. */
type Main = {
  $type: 'live.drome.sketch'
  title: string

  /**
   * The source code of the live-coded music sketch.
   */
  code: string
  description?: string
  tags?: string[]

  /**
   * AT URI of the sketch this was forked from.
   */
  origin?: l.AtUriString

  /**
   * AT URI of the prior version of this sketch.
   */
  previousVersion?: l.AtUriString
  createdAt: l.DatetimeString
}

export type { Main }

/** A live-coded music sketch. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 256 }),
    code: l.string({ maxLength: 100000 }),
    description: l.optional(l.string({ maxLength: 2048 })),
    tags: l.optional(l.array(l.string({ maxLength: 64 }), { maxLength: 8 })),
    origin: l.optional(l.string({ format: 'at-uri' })),
    previousVersion: l.optional(l.string({ format: 'at-uri' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
